config/routes.rb
Rails.application.routes.draw do
  get 'gardens/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :households, only: [:show, :new, :create, :edit, :update, :destroy] do
    get 'calendar', to: 'calendars#show'
    member do
      post :timetable
      get 'chores'
    end
    collection do
      get :search_users
    end
  end


  resources :users, only: [:index, :show] do
    get 'garden', to: 'gardens#show'

    member do

    end
  end

  get 'gardens/water', to: 'gardens#water', as: :water

  resources :submissions, only: [:new, :create, :edit, :update,]







  # Routes for users
  # resources :users, only: [:index, :show, :edit, :update] do
  #   resources :submissions, only: [:index, :show, :create, :edit, :update, :destroy]
  # end

  # # Routes for households
  # resources :households, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  #   resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # end

  # # Direct routes for tasks if needed outside of households
  # resources :tasks, only: [:destroy]

  # # Direct routes for submissions if needed outside of users
  # resources :submissions, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<!-- app/views/shared/_ios_pwa_links.html.erb -->
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<%= turbo_frame_tag :navbar do%>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="user-profile-achievements">
      <div class="user-profile-coins d-flex">
        <%= image_tag("navbar-droplet.png") %>
        <p> <% if current_user.present? && current_user.points.present?  %>
            <%= current_user.points %> water
          <% end %>
        </p>
      </div>
      <div class="user-profile-badges d-flex">
        <%= image_tag("navbar-flower.png")%>
        <p> <% if current_user.present? && current_user.badges.present? %>
            <%= current_user.badges.count %> flowers
            <% else %>
            1 flowers
          <% end %>
        </p>
      </div>
    </div>
    <div >
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <%= cl_image_tag(current_user.photo.key, class: "avatar", alt: "dropdown menu", style: "width: 40px; height: 40px; margin: 0px;")%>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if current_user != nil %>
            <li class="nav-item">
              <%= link_to "My house", household_path(current_user), class: "nav-link", data: { turbo_frame: "_top"} %>
            </li>
            <li class="nav-item">
              <%= link_to "My page", user_path(current_user), class: "nav-link", data: { turbo_frame: "_top"} %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete, turbo_frame: "_top"}, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link", data: { turbo_frame: "_top"} %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_navbar_footer.html.erb
<div class="navbar-footer">

  <!-- Seedling Icon -->
  <div class="navbar-footer-item <%= 'active' if current_page?(user_garden_path(current_user)) %>">
    <%= link_to user_garden_path(current_user) do %>
      <i class="fa-solid fa-seedling navbar-footer-btn" style="font-size: 24px;"></i>
    <% end %>
  </div>
  <!-- House Icon -->
  <div class="navbar-footer-item <%= 'active' if current_page?(household_path(current_user)) || current_page?(chores_household_path(current_user.household)) %>">
    <%= link_to household_path(current_user) do %>
      <i class="fa-solid fa-house-user navbar-footer-btn" style="font-size: 24px;"></i>
    <% end %>
  </div>
  <!-- Task List Icon -->
  <div class="navbar-footer-item <%= 'active' if current_page?('/tasks') %>">
    <%= link_to '/tasks' do %>
      <i class="fa-solid fa-list navbar-footer-btn" style="font-size: 24px;"></i>
    <% end %>
  </div>
  <!-- Calendar Icon -->
  <div class="navbar-footer-item <%= 'active' if current_page?(household_calendar_path(current_user.household)) %>">
    <%= link_to household_calendar_path(current_user.household) do %>
      <i class="fa-solid fa-calendar navbar-footer-btn" style="font-size: 24px;"></i>
    <% end %>
  </div>
</div>

app/views/shared/_progress_bar.html.erb
<div class="d-flex justify-content-center">
  <div class="progress m-1">
    <div class="progress-bar" role="progressbar" style="width: <%= @progress_percentage %>%;" aria-valuenow="<%= @progress_percentage %>" aria-valuemin="0" aria-valuemax="100">
      <%= @progress_percentage %> %
    </div>
  </div>

</div>

<div class="d-flex justify-content-center">
  <% if @progress_percentage == 0 %>
    <p class="m-0">No chores completed so far...</p>
  <% elsif @progress_percentage <= 25 %>
    <p class="m-0">You're on the right track...</p>
  <% elsif @progress_percentage <= 40 %>
    <p class="m-0">You're almost half-way...</p>
  <% elsif @progress_percentage <= 75 %>
    <p class="m-0">You're doing well...</p>
  <% elsif @progress_percentage <= 99 %>
    <p class="m-0">You're almost done...</p>
  <% elsif @progress_percentage <= 100 %>
    <p class="m-0">All chores completed... for now</p>
  <% end %>
</div>