config/routes.rb
Rails.application.routes.draw do
  get 'gardens/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :households, only: [:show, :new, :create, :edit, :update, :destroy] do
    get 'calendar', to: 'calendars#show'
    member do
      post :timetable
      get 'chores'
    end
    collection do
      get :search_users
    end
  end


  resources :users, only: [:index, :show] do
    get 'garden', to: 'gardens#show'

    member do

    end
  end

  get 'gardens/water', to: 'gardens#water', as: :water

  resources :submissions, only: [:new, :create, :edit, :update,]







  # Routes for users
  # resources :users, only: [:index, :show, :edit, :update] do
  #   resources :submissions, only: [:index, :show, :create, :edit, :update, :destroy]
  # end

  # # Routes for households
  # resources :households, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  #   resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # end

  # # Direct routes for tasks if needed outside of households
  # resources :tasks, only: [:destroy]

  # # Direct routes for submissions if needed outside of users
  # resources :submissions, only: [:destroy]
end

app/views/pages/_flower_animation.html.erb
<%# <h1>Image with animation</h1>
<p>app/javascript/controllers/image_animation_controller.js</p> %>

<h1>bud images</h1>
 <img src="<%= asset_path('bud1.png') %>" class ="flower_s">

<div class="container">
  <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('bud1.png'), asset_path('bud2.png')].to_json %>">
    <img src="<%= asset_path('bud1.png') %>" data-image-animation-target="image" alt="Flower animation" class ="flower_s">
  </div>
</div>

<h1>flower 1</h1>

<img src="<%= asset_path('flower1.png') %>" class ="flower_s">

<div class="container">
  <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('flower1.png'), asset_path('flower2.png'), asset_path('flower1.png'), asset_path('flower3.png')].to_json %>">
    <img src="<%= asset_path('flower1.png') %>" data-image-animation-target="image" alt="Flower animation" class ="flower_s">
  </div>
</div>

<h1>flower 2</h1>

<img src="<%= asset_path('pink1.png') %>" class ="flower_s">

<div class="container">
  <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('pink1.png'), asset_path('pink2.png'), asset_path('pink1.png'), asset_path('pink3.png')].to_json %>">
    <img src="<%= asset_path('pink1.png') %>" data-image-animation-target="image" alt="Flower animation" class ="flower_s">
  </div>
</div>

<h1>Dead</h1>

<img src="<%= asset_path('deadplant1.png') %>" class ="flower_s">

<div class="container">
  <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('deadplant1.png'), asset_path('deadplant2.png'), asset_path('deadplant3.png'), asset_path('deadplant4.png')].to_json %>">
    <img src="<%= asset_path('deadplant1.png') %>" data-image-animation-target="image" alt="Flower animation" class ="flower_s">
  </div>
</div>




<!--Description-->
<div class = "homebody-2">
  <div class="info-card-wrapper container justify-content-center m-3">
    <div class="info-card align-items-center">
      <P>Welcome to Chore Quest 🌸<P>
      <ul>
      <li>Track & Complete Your Chores

      <li>Earn Rewards/Complete chores to earn beautiful flowers & water points.

      <li>Grow Your Garden /Use your points to grow and care for your flowers!
      </ul>
      <p>Start making chores fun and rewarding today!</p>

    </div>
     <!--grass front--->
    <img src="<%= asset_path('header_img.png') %>" alt="header" class="sub-image-front">
  </div>
</div>

app/views/pages/home.html.erb
<div class = "homebody">

  <div class="container justify-content-center m-3" style="position: relative;">
    <img src="<%= asset_path('grass_bg.png') %>" alt="grass" class="image-back">

    <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('pakkun1.png'), asset_path('pakkun2.png')].to_json %>">
      <img src="<%= asset_path('pakkun1.png') %>" data-image-animation-target="image" alt="Flower animation" class="image-back-pakkun">
    </div>

    <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('flower1.png'), asset_path('flower2.png'),asset_path('flower1.png'),asset_path('flower3.png')].to_json %>">
      <img src="<%= asset_path('flower1.png') %>" data-image-animation-target="image" alt="Flower animation" class="image-back-sun">
    </div>

  <div class="homecard align-items-center">
    <div class = "align-items-center">
      <h1 class ="title mt-5">Chore</h1>
      <h1 class ="title-bottom mb-3">Quest</h1>
    </div>
      <div class = "text-center">
      <% if current_user.nil? %>
      <%= link_to "Set up household",new_household_path, class:"btn btn-success homebutton p-2 px-3"%>
      <div>
      <%= link_to "Sign Up",new_user_registration_path, class:"btn btn-danger homebutton p-2 px-3 mt-3"%>
      </div>
      <% elsif current_user.household.nil?%>
      <%= link_to "Set up household",new_household_path, class:"btn btn-success homebutton p-2 px-3"%>
      <div>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-danger homebutton p-2 px-3 mt-3" %>
      </div>
      <% else %>
      <%= link_to "See your house",chores_household_path(current_user.household), class:"btn btn-success homebutton p-2 px-3"%>
      <div>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-danger homebutton p-2 px-3 mt-3" %>
      </div>
      <% end %>
  </div>
  </div>
    <!--grass front--->
    <img src="<%= asset_path('grass_front.png') %>" alt="grass" class="image-front">
    <!--big white flower front--->
    <div data-controller="image-animation"
      data-image-animation-images="<%= [asset_path('white1.png'), asset_path('white2.png'),asset_path('white3.png'), asset_path('white4.png'),asset_path('white3.png'), asset_path('white2.png')].to_json %>">
      <img src="<%= asset_path('white4.png') %>" data-image-animation-target="image" alt="Flower animation" class ="flower1-front">
    </div>
    <!--medium right flower front--->
    <img src="<%= asset_path('white4.png') %>" alt="grass" class="flower2-front">
    <!--medium left flower front--->
    <img src="<%= asset_path('white4.png') %>" alt="grass" class="flower3-front">
  </div>
</div>