config/routes.rb
Rails.application.routes.draw do
  get 'gardens/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :households, only: [:show, :new, :create, :edit, :update, :destroy] do
    get 'calendar', to: 'calendars#show'
    member do
      post :timetable
      get 'chores'
    end
    collection do
      get :search_users
    end
  end


  resources :users, only: [:index, :show] do
    get 'garden', to: 'gardens#show'

    member do

    end
  end

  get 'gardens/water', to: 'gardens#water', as: :water

  resources :submissions, only: [:new, :create, :edit, :update,]







  # Routes for users
  # resources :users, only: [:index, :show, :edit, :update] do
  #   resources :submissions, only: [:index, :show, :create, :edit, :update, :destroy]
  # end

  # # Routes for households
  # resources :households, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  #   resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # end

  # # Direct routes for tasks if needed outside of households
  # resources :tasks, only: [:destroy]

  # # Direct routes for submissions if needed outside of users
  # resources :submissions, only: [:destroy]
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  def show
    @all_calendar_tasks = current_user.household.submissions.where(deadline: Date.today.beginning_of_month..Date.today.next_month.end_of_month)
    @household = current_user.household
    @user = current_user
    @users = @household.users
  end

end

app/views/calendars/show.html.erb
<div class="household-show">
  <!-- title -->
  <div class="household-show-title" style=" width: 100%;">
    <h1><%= @household.title %>'s <br/> house <%= link_to '', edit_household_path(current_user.household), class: "fa-solid fa-pen-to-square", style: "font-size: 30px; opacity: 50%;" %></h1>
  </div>
  <!-- Members section -->
  <div class="household-show-members">
    <div class="user-show-members">
      <div class="d-flex">
        <% @users.each do |user|%>
          <div class="d-flex">
            <div class="user-show-member-profiles">
              <div class="profile-pic-placeholder">
                <%= cl_image_tag(user.photo.key, class: "profile-pic") %>
              </div>
              <p class="mb-0" ><%= user.username %></p>
            </div>
          </div>
        <% end %>
        <!-- member add modal button -->
        <div class="d-flex justify-content-center">
          <button type="button" class="btn" data-toggle="modal" data-target="#memberModal", style="border-radius: 32px; border: 1px solid black; align-content: center; width: 40px; height: 40px; margin-left: 8px; margin-right: 8px;">
            <i class="fa-solid fa-plus" style="font-size: 18px; text-align: center;"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- member add modal form -->
    <div class="modal fade mt-3" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="memberModalLabel">Add New Member</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render '/users/form' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>


</div>

<div class="household-show pt-2">
  <div class="household-show-calendar mt-3">

    <!-- Updated Calendar -->
    <div class="d-flex justify-content-center text-align-center mb-2">
      <h2  style="font-family: 'Jersey 20'; font-size: 40px; font-style: normal;" >Calendar<i class="fa-solid fa-calendar-days mx-2" style="font-size: 24px;"></i></h2>
    </div>
    <%= week_calendar(events: @all_calendar_tasks, attribute: :deadline) do |date, submissions| %>
      <div class="day" data-bs-toggle="modal" data-bs-target="#modal-<%= date.to_s%>">
        <%= date.day %>
        <% if submissions.any? %>
          <% unique_users = submissions.map(&:user).uniq %>
          <% unique_users.each do |user| %>
            <% user_color = "##{Digest::MD5.hexdigest(user.id.to_s)[0..5]}" %>
            <div class="task" style="background-color: <%= user_color %>; color: #fff;">
              <%= user.username %>
            </div>
          <% end %>
        <% end %>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="modal-<%= date.to_s%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel"><%= date %></h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <% if submissions.any? %>
                <% submissions.group_by(&:user).each do |user, user_submissions| %>
                  <div class="user-tasks text-start" style="font-size: 20px">
                    <strong><%= user.username.capitalize %>'s chores</strong>
                    <ul>
                      <% user_submissions.each do |submission| %>
                        <li><%= submission.task.title %>: <%= submission.task.frequency %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>
              <% else %>
                <p>No Chores for this date.</p>
              <% end %>
            </div>
            <div class="modal-footer">
              <%# <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" style= "border-radius: 32px; border: 1px black solid; margin-bottom: 26px;">Close</button> %>
              <%= link_to 'See your chores', tasks_path(current_user.tasks), class: "btn btn-primary", style: "border-radius: 32px; border: 1px black solid; margin-bottom: 26px;" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div class="d-flex justify-content-center mt-4">
  <%= link_to 'My To-do list', '/tasks', class: "btn btn-primary px-3 py-2", style: "border-radius: 50px; border: 1px black solid" %>
</div>