config/routes.rb
Rails.application.routes.draw do
  get 'gardens/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :households, only: [:show, :new, :create, :edit, :update, :destroy] do
    get 'calendar', to: 'calendars#show'
    member do
      post :timetable
      get 'chores'
    end
    collection do
      get :search_users
    end
  end


  resources :users, only: [:index, :show] do
    get 'garden', to: 'gardens#show'

    member do

    end
  end

  get 'gardens/water', to: 'gardens#water', as: :water

  resources :submissions, only: [:new, :create, :edit, :update,]







  # Routes for users
  # resources :users, only: [:index, :show, :edit, :update] do
  #   resources :submissions, only: [:index, :show, :create, :edit, :update, :destroy]
  # end

  # # Routes for households
  # resources :households, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
  #   resources :tasks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  # end

  # # Direct routes for tasks if needed outside of households
  # resources :tasks, only: [:destroy]

  # # Direct routes for submissions if needed outside of users
  # resources :submissions, only: [:destroy]
end

app/models/household.rb
class Household < ApplicationRecord
  belongs_to :user
  has_many :users, dependent: :destroy
  has_many :tasks
  has_many :submissions, through: :tasks
  validates :title, presence: true


end

app/controllers/households_controller.rb
class HouseholdsController < ApplicationController
  def show
    @user = current_user
    @household = @user.household
    @users = @household.users || []
    @tasks = @household.tasks.order(created_at: :desc)
    @task = Task.new
    @members = User.all
    @completed_submissions = @household.submissions.where(status: "completed").order(updated_at: :desc)

    @my_calendar_tasks = current_user.submissions.where(deadline: Date.today.beginning_of_month..Date.today.next_month.end_of_month)
    @all_calendar_tasks = current_user.household.submissions.where(deadline: Date.today.beginning_of_month..Date.today.next_month.end_of_month)
  end

  def new
    @household = Household.new
    @users = User.all
  end

  def create
    @household = Household.new(household_params)
    @household.user = current_user

    if @household.save
      # Assign selected users to the household
      selected_users = User.where(id: params[:household][:user_ids])
      selected_users.each do |user|
        user.household = @household
        user.save
      end

      redirect_to household_path(@household), notice: 'Household was successfully created.'
    else
      @users = User.all
      render :new
    end
  end

  def edit
    @user = current_user
    @household = @user.household
  end

  def update
    @user = current_user
    @household = @user.household
    if @household.update(household_params)
      redirect_to household_path
    else
      render 'household/form', status: :unprocessable_entity
    end
  end

  def destroy

  end

  def timetable
    @household = Household.find(params[:id])
    TimetableService.new(@household).call
    redirect_to chores_household_path(@household)
  end

  def search_users
    Rails.logger.debug "Search action called with query: #{params[:query]}"

    if params[:query].present?
      @users = User.where("username LIKE ?", "%#{params[:query]}%")
    else
      @users = User.none
    end

    Rails.logger.debug "Users found: #{@users.pluck(:username)}"

    respond_to do |format|
      format.json { render json: @users.pluck(:id, :username) }
    end
  end

  def chores
    @user = current_user
    @household = @user.household
    @users = @household.users || []
    @tasks = @household.tasks.order(created_at: :desc)
    @task = Task.new
    @members = User.all

  end

  def view_tasks
    @users = User.all
  end

  private

  def household_params
    params.require(:household).permit(:title, user_ids: [])
  end

end

app/views/households/_add_tasks.html.erb
<div class="p-2">
  <h1>Add Chores</h1>
  <div class="add-task-categories py-3">
    <h5>Suggested Chores</h5>
    <%= render 'tasks/suggested_tasks' %>
  </div>
  <div class="add-task-categories py-3">
    <h5>Custom Chores</h5>
    <!-- Modal button -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#taskModal", style="border-radius: 32px; border: 1px black solid; width: 100%;">
      <i class="fa-solid fa-circle-plus"></i>Create Custom Chores
    </button>
    <!-- Modal  -->
    <div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="taskModalLabel">Add New Chores</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render 'tasks/form', task: @task %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="add-task-categories py-3">
    <h5>Added Chores</h5>
    <% @tasks.each do |task| %>
      <div class="card-product d-flex align-items-center p-3">
        <% if task.submissions.first.nil? %>
          <span class="badge bg-danger rounded-circle p-3 ms-auto" style="font-size: 1.5em;">
            <i class="fa-regular fa-calendar-xmark" style="font-size: 1.2em;"></i>
          </span>
        <% else %>
          <span class="badge bg-success rounded-circle p-3 ms-auto" style="font-size: 1.5em;">
            <i class="fa-solid fa-calendar-check" style="font-size: 1.2em;"></i>
          </span>
        <% end %>
        <div class="card-product-infos flex-grow-1">
          <h2><%= task.title %></h2>
          <p><%= task.frequency %></p>
        </div>
        <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Delete task?" }, class: "btn btn-danger mx-2" do %>
          <i class="fa-solid fa-trash-can"></i>
        <% end%>
      </div>
    <% end %>
  </div>
  <div class="add-task-categories py-3">
    <%= link_to timetable_household_path(current_user.household), data: { turbo_method: :post, turbo_confirm: "Generate now?" }, style:"border-radius: 32px; border: 1px black solid;", class: "btn btn-warning p-3" do %>
      <i class="fa-regular fa-calendar"></i> Assign Chores
    <% end %>
  </div>
</div>

app/views/households/_completed_task_card.html.erb
<div class="submission-post" style="border-bottom-left-radius: 12px; border-bottom-right-radius: 12px;" >

  <div class="post-top">
    <% if submission.user.photo.attached? %>
      <div class="d-flex">
        <%= cl_image_tag submission.user.photo.key, class: 'img-fluid rounded-circle me-3', alt: 'User Photo', style: 'width: 40px; height: 40px;' %>
        <h5 style="margin: auto 0;"><%= submission.user.username %></h5>
      </div>
    <% else %>
      <div class="d-flex">
        <img src="path/to/default-profile-photo.jpg" class="img-fluid rounded-circle me-3" alt="Default User Photo" style="width: 40px; height: 40px;">
        <h5><%= submission.user.username %></h5>
      </div>
    <% end %>
  </div>

  <% if submission.user.badges.any? %>
    <% most_recent_badge = submission.user.badges.last %>
    <% if most_recent_badge %>
      <div class="d-flex" style="padding: 10px; width: 100%; margin-top: 8px; background-color: #F4F4F4; border-radius: 16px;">
        <div>
          <img src="<%= asset_path('bud1.png') %>" style="width: 80px; height: 60px; object-fit: cover; object-position: bottom;" alt="bud">
        </div>
        <div>
          <h5>I've earned a flower!</h5>
          <p style="margin-bottom: 0px;">Head to the garden to water it</p>
        </div>
      </div>
    <% end %>
  <% end %>



  <div class="post-top">
    <% if submission.user.photo.attached? %>
      <div class="d-flex">
        <%= cl_image_tag submission.user.photo.key, class: 'img-fluid rounded-circle me-3', alt: 'User Photo', style: 'width: 40px; height: 40px;' %>
        <h5 style="margin: auto 0;"><%= submission.user.username %></h5>
      </div>
    <% else %>
      <div class="d-flex">
        <img src="path/to/default-profile-photo.jpg" class="img-fluid rounded-circle me-3" alt="Default User Photo" style="width: 40px; height: 40px;">
        <h5><%= submission.user.username %></h5>
      </div>
    <% end %>
  </div>
  <% if submission.photo.attached? %>
    <%= cl_image_tag submission.photo.key, class: 'img1', alt: 'Submission Photo' %>
  <% else %>
    <div style="width: 100%; height: 100px; background-color: gray;">
      <p style="margin: 0 auto;">No photo available</p>
    </div>
  <% end %>
  <h5 class="post-title"><strong>Chore:</strong> <%= submission.task.title %></h5>
  <p class="post-text">
    <strong>Date:</strong> <%= submission.updated_at.strftime("%d %b %Y %H:%M") %>
  </p>
</div>

app/views/households/_member_form.html.erb
<div class="form container w-50 mt-3" style="background-color: white; border-radius: 15px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
  <h2>Add a member</h2>
  <form>
    <label for="username">Members' username:</label><br>
    <input type="text" id="fname" name="username" class="mb-3"><br>
    <input type="submit" value="Submit" class="mb-3">
  </form>
</div>

app/views/households/_view_tasks.html.erb
<div class="p-2">
  <h1>Today's Chores</h1>
  <%= Date.today %>
  <div class="view-task-categories py-3">
  </div>
    <div class="border">
      <% @users.each do |user|%>
        <img style="width: 40px;" src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
        <% user.username %>
      <% end %>
    </div>

</div>

app/views/households/chores.html.erb
<div class="household-show">
  <!-- title -->
  <div class="household-show-title" style=" width: 100%;">
    <h1><%= @household.title %>'s <br/> house <%= link_to '', edit_household_path(current_user.household), class: "fa-solid fa-pen-to-square", style: "font-size: 30px; opacity: 50%;" %></h1>
  </div>
  <!-- Members section -->
  <div class="household-show-members">
    <div class="user-show-members">
      <div class="d-flex">
        <% @users.each do |user|%>
          <div class="d-flex">
            <div class="user-show-member-profiles">
              <div class="profile-pic-placeholder">
                <%= cl_image_tag(user.photo.key, class: "profile-pic") %>
              </div>
              <p class="mb-0" ><%= user.username %></p>
            </div>
          </div>
        <% end %>
        <!-- member add modal button -->
        <div class="d-flex justify-content-center">
          <button type="button" class="btn" data-toggle="modal" data-target="#memberModal", style="border-radius: 32px; border: 1px solid black; align-content: center; width: 40px; height: 40px; margin-left: 8px; margin-right: 8px;">
            <i class="fa-solid fa-plus" style="font-size: 18px; text-align: center;"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- member add modal form -->
    <div class="modal fade mt-3" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="memberModalLabel">Add New Member</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render '/users/form' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="chores-box">
    <div class="d-flex justify-content-between align-items-center">
      <div class="flex-colum text-start">
        <h2>Chores </h2>

          <% if @tasks.count == 0 %>
            <p> No chores scheduled</p>
          <% else %>
            <p class="mb-0"><strong><%= @tasks_with_submissions_count = @tasks.joins(:submissions).distinct.count %></strong> scheduled!</p>
          <% end %>

      </div>


        <%= link_to timetable_household_path(current_user.household), data: { turbo_method: :post, turbo_confirm: "Generate now?" }, style:"border-radius: 32px; border: 1px black solid;", class: "btn btn-warning" do %>
          Schedule
        <% end %>



    </div>
  </div>

  <% if @tasks.first.nil? %>
    <h5>Add some chores!</h5>
  <% end %>
  <!-- Add Custom and Add Suggested collapse -->

  <div data-controller = "collapse">
    <p class="d-inline-flex gap-1">
      <a class="btn btn-primary" style="border-radius: 32px; border: 1px solid black;" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample" data-action="click->collapse#toggleForm">
        + Custom
      </a>
      <% if @household.submissions.first.nil? %>
      <a class="btn btn-primary" style="border-radius: 32px; border: 1px solid black;" data-bs-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseExample" data-action="click->collapse#toggleSuggested">
        + Suggested
      </a>
      <% end %>
    </p>
    <div class="collapse" id="addCustom" data-collapse-target="form">
      <div class="card card-body">
        <%= render 'tasks/form', task: @task %>
      </div>
    </div>
    <div class="collapse" id="addSuggested" data-collapse-target="suggested">
      <div class="card card-body">
        <%= render 'tasks/suggested_tasks'%>
      </div>
    </div>
    <% unless @household.submissions.first.nil? %>
        <%= link_to household_calendar_path(current_user.household), style:"border-radius: 32px; border: 1px black solid;", class: "btn btn-warning" do %>
          <i class="fa-regular fa-calendar"></i> View Timetable
        <% end %>
        <% end %>
  </div>



      <% if @tasks.count > 0 && @tasks.first.submissions.first.nil? %>
      <h3>Un-scheduled Chores</h3>
      <p>Schedule some tasks!</p>
      <% end %>

  <div class="add-task-categories pt-3">


    <% @tasks.each do |task| %>

      <% if task.submissions.first.nil? %>


        <div class="card-product d-flex p-2" style="color: gray; border: 1px gray solid; width: 100%;" >
          <div class="d-flex align-items-center">
            <span class="badge bg-primary  p-2 m-2" style="font-size: 1em;">
              <i class="fa-regular fa-calendar-xmark" style="font-size: 1.2em;"></i>
            </span>
          </div>

          <div class="card-product-infos flex-grow-1 ms-2" >
            <h2><%= task.title %></h2>
            <p><%= task.frequency %></p>
          </div>

          <div class="d-flex align-items-center">
            <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Delete task?" }, class: "btn mx-2", style: "background-color: #F4F4F4" do %>
              <i class="fa-solid fa-trash-can",  style="color: gray" ></i>
            <% end %>
          </div>

        </div>

      <% else %>
      <% end %>
    <% end %>

    <% unless @tasks.first.nil? %>

    <% unless @household.submissions.first.nil? %>
    <h3 class="mt-4">Scheduled Chores</h3>
    <% end %>

    <% @tasks.each do |task| %>
      <% if task.submissions.first.nil? == false %>

        <div class="card-product d-flex p-2" style="opacity: 100%; background-color: #FFE795; width: 100%;" >
          <div class="d-flex align-items-center">
            <span class="badge bg-warning  p-2 m-2" style="font-size: 1em;">
              <i class="fa-solid fa-calendar-check" style="font-size: 1.2em;"></i>
            </span>
          </div>

          <div class="card-product-infos flex-grow-1 ms-2" >
            <div style="schedule-tasks">
              <h2><%= task.title %></h2>
              <p><%= task.frequency %></p>
            </div>
          </div>
          <div class="d-flex align-items-center">
            <%= link_to task_path(task), data: { turbo_method: :delete, turbo_confirm: "Delete task?" }, class: "btn mx-2", style: "background-color: #F4F4F4" do %>
              <i class="fa-solid fa-trash-can", style="color: black"></i>
            <% end%>
          </div>

        </div>
      <% end %>
    <% end %>
    <% end %>
  </div>


</div>

app/views/households/create.html.erb
<h1>Households#create</h1>
<p>Find me in app/views/households/create.html.erb</p>

app/views/households/destroy.html.erb
<h1>Households#destroy</h1>
<p>Find me in app/views/households/destroy.html.erb</p>

app/views/households/edit.html.erb
<div class="household-edit-style">
  <%# <h1>Households#edit</h1>
  <p>Find me in app/views/households/edit.html.erb</p> %>

  <h2>Edit a household</h2>
  <%= simple_form_for @household do |f| %>
    <%= f.input :title %>
    <div class="edit" style="display: flex; justify-content: center;">
      <%= f.submit "Confirm Edit", class: "btn btn-primary", style: "border-radius: 32px; border: 1px black solid;"%>
    </div>
  <% end %>
</div>

app/views/households/new.html.erb
<div class="household-new-style">
  <%= simple_form_for @household do |f| %>
    <div class="form-group mb-3">
      <%= f.label :title, "Household Name", style: "font-weight:bold;" %>
      <%= f.input :title, placeholder: "Name your house", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :user_ids, "Invite Members", style: "font-weight:bold;" %>
      <div class="dropdown">
        <input type="text" id="user-search" placeholder="Search for your housemates" class="form-control dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <ul id="user-results" class="dropdown-menu mt-2"></ul>
      </div>
      <div id="selected-users" class="mt-2"></div>
    </div>

    <!-- Hidden input to store selected user IDs -->
    <%= f.hidden_field :user_ids, value: current_user.id, id: 'user-ids-field', multiple: true %>
    <br>
    <div class="form-group" style="display: flex; justify-content: center;">
      <%= f.submit "Get started", class: "btn btn-primary", style: "border-radius: 32px; border: 1px black solid;" %>
    </div>
  <% end %>
</div>

app/views/households/show.html.erb
<div class="household-show">
  <!-- title -->
  <div class="household-show-title" style=" width: 100%;">
    <h1><%= @household.title %>'s <br/> house <%= link_to '', edit_household_path(current_user.household), class: "fa-solid fa-pen-to-square", style:"font-size: 30px; opacity:50%" %></h1>
  </div>
  <!-- Members section -->
  <div class="household-show-members">
    <div class="user-show-members">
      <div class="d-flex">
        <% @users.each do |user|%>
          <div class="d-flex">
            <div class="user-show-member-profiles">
              <div class="profile-pic-placeholder">
                <%= cl_image_tag(user.photo.key, class: "profile-pic") %>
              </div>
              <p class="mb-0" ><%= user.username %></p>
            </div>
          </div>
        <% end %>
        <!-- member add modal button -->
        <div class="d-flex justify-content-center">
          <button type="button" class="btn" data-toggle="modal" data-target="#memberModal", style="border-radius: 32px; border: 1px solid black; align-content: center; width: 40px; height: 40px; margin-left: 8px; margin-right: 8px;">
            <i class="fa-solid fa-plus" style="font-size: 18px; text-align: center;"></i>
          </button>
        </div>
      </div>
    </div>
    <!-- member add modal form -->
    <div class="modal fade mt-3" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="memberModalLabel">Add New Member</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render '/users/form' %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- TASKS -->
  <div class="household-show-tasks">
    <div class="d-flex justify-content-between align-items-center">
      <div class="flex-column text-start">
        <h2>Chores</h2>
        <% if @tasks.count == 0 %>
          <p> No chores scheduled</p>
        <% else %>
          <p class="mb-0"> <strong><%= tasks_with_submissions_count = @tasks.joins(:submissions).distinct.count  %> </strong> scheduled!</p>
        <% end %>
      </div>
      <%= link_to chores_household_path(@household), class: "btn btn-warning", style: "border-radius: 32px; border: 1px black solid;" do %>
        + Add
      <% end %>
    </div>
  </div>
</div>
<!-- Feed of completed tasks -->
<div class="submission-container" >

  <h2 class="text-center" style="padding-top: 8px; padding-bottom: 8px; font-family: 'Jersey 20'; font-size: 40px; font-style: normal; background-color: #DA75FF; border-top-left-radius: 13px; border-top-right-radius: 13px;">Completed Chores</h2>
  <% if @completed_submissions.any? %>
    <div class="completed-tasks-feed" style="border-radius: 16px;">
      <% @completed_submissions.each do |submission| %>
        <%= render partial: 'completed_task_card', locals: { submission: submission } %>
      <% end %>
    </div>
  <% else %>
    <p class="text-center">No Chores completed yet.</p>
  <% end %>
</div>

app/views/households/update.html.erb
<h1>Households#update</h1>
<p>Find me in app/views/households/update.html.erb</p>